---
abstract: 'Another RDF Encoding Form'
author:
  - 'Jakob Voß'
build_requires:
  JSON: 0
  RDF::Trine: 0
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-aREF
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  RDF::NS: 20130816
  perl: v5.12.0
resources:
  bugtracker: https://github.com/nichtich/RDF-aREF/issues
  homepage: https://github.com/nichtich/RDF-aREF
  repository: https://github.com/nichtich/RDF-aREF.git
version: 0.15
x_contributors:
  - 'Jakob Voss <jakob@nichtich.de>'
  - 'Jakob Voss <voss@gbv.de>'
